#!/usr/bin/env python3
"""Unified Multi-Project Real Build Validation Harness (RQ4).

Validates skbuild presence conditions against actual build graphs across:
1. BusyBox (real compiler build)
2. coreboot (real compiler build on QEMU x86 i440fx)
3. Barebox (real Make evaluation on Sandbox target)
4. Das U-Boot (real Make evaluation on Sandbox target)
"""

import json
import os
import pathlib
import re
import subprocess
import sys
import time
import z3

# Set up PYTHONPATH
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

import helpers.vcommon as CM
import helpers.zsolver as zsolver
import settings
from alg import Run


def extract_compiled_objects_from_make(root_dir, defconfig_target="sandbox_defconfig"):
    root_path = pathlib.Path(root_dir).resolve()
    # 1. Run defconfig
    subprocess.run(["make", defconfig_target], cwd=root_path, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    # 2. Run dry-run make to collect all compiled object targets
    proc = subprocess.run(["make", "-n"], cwd=root_path, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    
    actual_objects = set()
    # Match patterns like '-o path/to/file.o' or 'CC path/to/file.o'
    for line in proc.stdout.splitlines():
        matches = re.findall(r"(?:-o|\s)\s*([a-zA-Z0-9_\-/\.]+\.(?:o|gen\.o|a))", line)
        for m in matches:
            m_path = pathlib.Path(m)
            if not str(m_path).startswith("scripts/"):
                actual_objects.add(str(m_path))
                
    return actual_objects


def validate_corpus_build(corpus_name, root_dir, defconfig_target):
    root_path = pathlib.Path(root_dir).resolve()
    print(f"\n=======================================================")
    print(f"Validating Ground Truth Build Predictions: {corpus_name}")
    print(f"=======================================================")

    runner = Run(root_path)
    tmpdir = runner.go()

    kbuilds = getattr(runner, 'all_kbuilds', getattr(runner, 'kbuilds', []))
    main_dir = getattr(runner, 'maindir', getattr(runner, 'main_dir', root_path))
    mysettings = getattr(runner, 'mysettings', None)

    # 1. Extract symbolic predictions
    target_objects = {}
    for kb in kbuilds:
        state = kb.state
        parent = kb.makefile.parent
        for v in state.target_files:
            if mysettings and v.name in mysettings.target_vars:
                continue
            for word, wcond in v.valconds.items():
                if isinstance(word, str) and (word.endswith('.o') or word.endswith('.a')):
                    try:
                        rel = str((parent / word).relative_to(main_dir))
                    except ValueError:
                        rel = str(word)
                    target_objects[rel] = wcond

    # 2. Read concrete .config generated by defconfig
    config_file = root_path / ".config"
    subprocess.run(["make", defconfig_target], cwd=root_path, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    
    active_configs = set()
    if config_file.exists():
        for line in config_file.read_text(errors='ignore').splitlines():
            line = line.strip()
            if line.startswith("CONFIG_") and "=y" in line:
                sym = line.split("=")[0]
                active_configs.add(sym)

    # 3. Evaluate symbolic presence conditions under concrete active_configs
    zs = zsolver.ZSolver(runner.mysettings)
    solver = z3.Solver()
    
    # Assert model assignments
    eval_model_dict = {}
    for kb in kbuilds:
        for name in kb.state.states:
            if name.startswith("CONFIG_"):
                zvar, optD = zs.get_sort(name)
                val = optD['y'] if name in active_configs else zs.undef_val
                eval_model_dict[zvar] = val

    predicted_present = set()
    for obj, cond in target_objects.items():
        if cond is zsolver.T or cond is True:
            predicted_present.add(obj)
        elif isinstance(cond, z3.ExprRef):
            # Substitute concrete values
            substs = [(k, v) for k, v in eval_model_dict.items()]
            val_expr = z3.substitute(cond, substs)
            val_simp = zsolver.simplify(val_expr)
            if z3.is_true(val_simp) or str(val_simp) == "y":
                predicted_present.add(obj)

    # 4. Extract actual compiled objects
    actual_compiled = extract_compiled_objects_from_make(root_path, defconfig_target)

    # 5. Reconcile TP, FP, FN, TN
    tp = predicted_present & actual_compiled
    fp = predicted_present - actual_compiled
    fn = actual_compiled - predicted_present
    
    # Filter FN/FP to relevant analyzed directories
    analyzed_parents = {str(kb.makefile.parent.relative_to(main_dir)) for kb in kbuilds if kb.makefile.parent != main_dir}
    filtered_fn = {f for f in fn if any(f.startswith(p + "/") for p in analyzed_parents)}
    filtered_fp = {f for f in fp if not f.startswith("scripts/")}

    precision = len(tp) / max(1, len(tp) + len(filtered_fp)) * 100.0
    recall = len(tp) / max(1, len(tp) + len(filtered_fn)) * 100.0

    print(f"Results for {corpus_name} ({defconfig_target}):")
    print(f"  Predicted Active: {len(predicted_present)}")
    print(f"  Actual Compiled in Scope: {len(tp | filtered_fn)}")
    print(f"  True Positives (TP): {len(tp)}")
    print(f"  False Positives (FP): {len(filtered_fp)}")
    print(f"  False Negatives (FN): {len(filtered_fn)}")
    print(f"  Precision: {precision:.1f}%")
    print(f"  Recall:    {recall:.1f}%")

    return {
        "corpus": corpus_name,
        "config_target": defconfig_target,
        "total_symbolic_targets": len(target_objects),
        "predicted_present": len(predicted_present),
        "tp": len(tp),
        "fp": len(filtered_fp),
        "fn": len(filtered_fn),
        "precision_pct": round(precision, 1),
        "recall_pct": round(recall, 1),
        "sample_fp": list(filtered_fp)[:5],
        "sample_fn": list(filtered_fn)[:5],
    }


def main():
    benchmarks = [
        ("Barebox (Sandbox)", "results/workspaces/barebox/source/barebox-2024.01.0", "sandbox_defconfig"),
        ("Das U-Boot (Sandbox)", "results/workspaces/uboot/source/u-boot-2024.01", "sandbox_defconfig"),
    ]

    results = []
    for name, path, cfg in benchmarks:
        if os.path.exists(path):
            r = validate_corpus_build(name, path, cfg)
            results.append(r)

    print("\n\n" + "="*80)
    print("REAL BUILD VALIDATION BENCHMARK RESULTS")
    print("="*80)
    print(json.dumps(results, indent=2))

    with open("results/sandbox_build_validations.json", "w") as f:
        json.dump(results, f, indent=2)


if __name__ == "__main__":
    main()
